#!/bin/bash

# Copyright (C) 2005 W. Michael Petullo <mike@flyn.org>
# Copyright (C) 2006 David Zeuthen <davidz@redhat.com>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2.

CRYPTSETUP=/sbin/cryptsetup

if [ ! -f $CRYPTSETUP ]; then
	echo org.freedesktop.Hal.Device.Volume.Crypto.TeardownError >&2
	echo Error tearing down $HAL_PROP_BLOCK_DEVICE - $CRYPTSETUP not found >&2
	exit 1
fi

if ! $CRYPTSETUP luksClose luks_crypto_$HAL_PROP_VOLUME_UUID  2> /dev/null; then
	echo org.freedesktop.Hal.Device.Volume.Crypto.TeardownError >&2
	echo Error tearing down $HAL_PROP_BLOCK_DEVICE - fs still mounted? >&2
	exit 1
fi

hal-set-property --udi=$UDI --key="info.callouts.remove" --strlist-rem="hal-luks-remove" > /dev/null 2>&1
