#!/bin/sh

path_mc="/sys/devices/system/cpu/sched_mc_power_savings"
path_smt="/sys/devices/system/cpu/sched_smt_power_savings"
val=0

case "$1" in
	true)
		echo "**sched policy powersave ON"
		val=1
		;;
	false)
		echo "**sched policy powersave OFF"
		val=0
		;;
esac

# Based on the values (1-enable, 0-disable) for these controls,
# sched groups cpu power will be determined for different domains.
# When power savings policy is enabled and under light load conditions,
# scheduler will minimize the physical packages/cpu cores carrying the
# load and thus conserving power

if [ -w "$path_mc" ] ; then
	echo $val > $path_mc
fi
if [ -w "$path_smt" ] ; then
	echo $val > $path_smt
fi

exit 0
