#!/bin/bash
#
# Author: tlinux team <t_os@tencent.com>
#
# chkconfig: 3 08 90
#
# description: System startup script for user
#
###BEGIN INIT INFO
# Required-Start:
# Should-Start:
# Default-Start-Level: 3
# Default-Stop-Level:
###END INIT INFO
case "$1" in
	start)
	if [ ! -x /etc/rc.d/boot.local ]; then
		echo "/etc/rc.d/boot.local is not exit!"
		exit 1
	fi
	touch /var/lock/subsys/bootlocal
	/etc/rc.d/boot.local &
	;;
	stop)
	;;
esac
