#!/bin/bash
vmwhat()
{
	if [ -d /proc/xen -a ! -f /proc/xen/capabilities ]; then
		echo "xen-domU"
		return 0
	elif [ -f /proc/xen/capabilities ]; then
		if grep -q "control_d" /proc/xen/capabilities; then
        		echo xen-dom0
		else
        		echo xen-domU
		fi
		return 0
	elif [ -f /sys/hypervisor/type ] &&
		grep -q "xen" $root/sys/hypervisor/type; then
		# Ordinary kernel with pv_ops.  There does not seem to be
		# enough information at present to tell whether this is dom0
		# or domU.  XXX
		echo xen
		echo beyond recognition dom0/domU
		return 0
	else
		echo "physical machine"
		return 1
	fi
}

vmwhat
