#!/bin/sh
# Log some extra information at the beginning of a suspend/resume cycle.
# TODO: Make this hook only run when PM_DEBUG is true?

. "${PM_FUNCTIONS}"

case "$1" in
        hibernate|suspend)
		[ -n "$PM_LOGFILE" ] || exit 0
		/bin/uname -a
		lsmod
		free
		;;
esac
