#!/bin/sh
# Synchronize system time with hardware time.
# TODO: Do modern kernels handle this correctly?  If so, we should detect that
#       and skip this hook.

. "${PM_FUNCTIONS}"

suspend_clock()
{
	/sbin/hwclock --systohc >/dev/null 2>&1 0<&1
}

resume_clock()
{
	/sbin/hwclock --hctosys >/dev/null 2>&1 0<&1
}

[ "$NEED_CLOCK_SYNC" ] || exit $NA

case "$1" in
	hibernate|suspend) suspend_clock ;;
	thaw|resume) resume_clock ;;
	*) exit $NA ;;
esac
