#!/bin/sh

. hal-functions

read value

hal_check_priv org.freedesktop.hal.power-management.set-powersave
hal_call_backend $value
if [ "$?" = "0" ]; then
    hal-set-property --udi $UDI --key "power_management.is_powersave_set" --bool "$value"
fi
