#!/bin/sh
#
# Copyright (C) 2007 Bastien Nocera <bnocera@redhat.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

. hal-functions

# Check for environment variables
if [ -z "$HAL_PROP_KILLSWITCH_ACCESS_METHOD" ]; then
        echo "org.freedesktop.Hal.Device.UnknownError" >&2
	echo "Missing or empty environment variable(s)." >&2
	echo "This script should be started by hald." >&2
	exit 1
fi

hal_check_priv org.freedesktop.hal.killswitch.$HAL_PROP_KILLSWITCH_TYPE
hal_exec_backend
