#!/bin/bash

# start udev
/sbin/start_udev

/bin/dbus-daemon --system

mount -o remount,rw,size=1G tmpfs /tmp
cat /proc/mounts > /etc/mtab

export VM=0 # running on a virtual machine?
grep -q "xvda" /proc/cmdline
if [ $? -eq 0 ]; then
	VM=1
fi

if [ $VM -ne 1 ]; then
	dmidecode | grep -Eqi "Manufacturer: innotek GmbH|Vendor: Parallels|Manufacturer: VMware"
	if [ $? -ne 0 ]; then
		dmidecode | grep -Eqi "Product Name: KVM|Product Name: CVM|Manufacturer: QEMU"
		if [ $? -eq 0 ]; then
			VM=1
		fi
	fi
fi

# draw out the install phase into a function
install_os() {
    echo "Enter installation mode"
	date > /tmp/tlinux-install.log
    /tos/install.sh 2>&1 | tee -a /tmp/tlinux-install.log
    rc=${PIPESTATUS[0]}

    if grep -q -v " rescue" /proc/cmdline; then
		grep -q -v "windows" /proc/cmdline
		if [ $? -eq 0 ]; then
		    mkdir /root_rw
            grep -q "rootsize=max" /proc/cmdline
            if [ $? -eq 0 -o $VM -eq 1 ] && [ -d /sys/firmware/efi ]; then
                rootpart=${INSDISK}2
            else
                rootpart=${INSDISK}1
            fi
 
            if [ -b /dev/$rootpart ]; then
                #umount /dev/$disk
                mount /dev/$rootpart /root_rw
                if [ -d /root_rw/var/log/ ]; then
                    cat /tmp/tlinux-install.log > /root_rw/var/log/tlinux-install.log
                    date >>/root_rw/var/log/tlinux-install.log
                    date > /root_rw/var/log/tlinux-install-dmesg.log
                    dmesg >>/root_rw/var/log/tlinux-install-dmesg.log
                    date >>/root_rw/var/log/tlinux-install-dmesg.log
                    umount /root_rw
                    return
                fi
            fi
                  
        fi
        # hardinstall always exit(reboot)
        grep -q installmethod=harddisk /proc/cmdline && exit 0
    fi
}

# installation os rescue
for t in $(cat /proc/cmdline); do
    case $t in
        rescue)
            echo "Enter rescue mode"
            /tos/rescue.sh
            break;
            ;;
	backup-mode)
	    echo "Enter backup mode"
	    date > /tmp/tlinux-backup.log
	    /tos/backup.sh 2>&1 | tee -a /tmp/tlinux-backup.log
	    mkdir /root_rw
            if [ -b /dev/sda1 ]; then
                #umount /dev/sda1
                mount /dev/sda1 /root_rw
                cat /tmp/tlinux-backup.log >>/root_rw/var/log/tlinux-backup.`date +"%Y-%m-%d-%H:%M"`.log
                date > /root_rw/var/log/tlinux-backup-dmesg.log
                dmesg >>/root_rw/var/log/tlinux-backup-dmesg.log
                date >>/root_rw/var/log/tlinux-backup-dmesg.log
                umount /root_rw
             fi
            # backup always exit(reboot)
            grep -q "backup-mode" /proc/cmdline && exit 0
	    break;
	    ;;
        installmethod=*)
            install_os
            break
            ;;
    esac
done

# in virt-install, /proc/cmdline is empty or filled by extra-args, no install would happen, 
# we set the default option is to install an os
grep -qE "rescue|backup|installmethod" /proc/cmdline
if [ $? -ne 0  ]; then
    install_os
fi


setsid /sbin/mingetty /dev/tty2 &
exec /bin/bash
