#!/bin/bash
#####################################################
#
# 20111123 lynnsong <lynnsong@tencent.com>
# -version 1.1
# -Modify: support suse, tlinux and xen
#
#####################################################
version=1.1

TMP1=$1
TMP2=$2
TMP3=$3
ETH1=`echo $TMP1|grep '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' `
MASK1=`echo $TMP2|grep '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' `
GATEWAY1=`echo $TMP3|grep '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' `

if [ -f /etc/SuSE-release ]; then
	ETH0_CONF="/etc/sysconfig/network/ifcfg-eth0"
	ETH1_CONF="/etc/sysconfig/network/ifcfg-eth1"
	SSH_36000="/etc/ssh2/sshd2_config"
	SSH_56000="/etc/ssh2/sshd2_config.l"
elif [ -f /etc/tlinux-release -o -f /etc/redhat-release ]; then
	ETH0_CONF="/etc/sysconfig/network-scripts/ifcfg-eth0"
	ETH1_CONF="/etc/sysconfig/network-scripts/ifcfg-eth1"
	SSH_36000="/etc/ssh/sshd_config"
	SSH_56000="/etc/ssh/sshd_config.l"
fi

usage()
{
	echo "USAGE:"
	echo "	$0 [eth1] [mask1] [gatewayl] [-f]"
	echo "	$0 [eth1] [mask1] [gatewayl] [eth0] [mask0] [gateway0] [-f]"
	echo "	$0 -V/--version"
	echo "	$0 -H/--help"
	rm /tmp/tmp.setip > /dev/null 2>&1
	exit 0
}

check_input()
{
	key=`echo "$*" | grep -e '[a-zA-Z]' | awk -F "." '{print $1}'`
      	if [ $key ]; then
        	usage
      	fi
        
      	for i in $*
      	do
		echo $i | awk -F "." '{print NF,$1,$2,$3,$4}' > /tmp/tmp.setip
                while read num one two three four	
      		do
        		if [ $num -ne 4 ]; then 
				echo -n "Network configuration input"
				echo -e "\t\t[\033[31m Error! \033[0m ]"        
           			usage 
        		fi
        		if [ -z "$one" -o -z "$two" -o -z "$three" -o -z "$four" ]; then
				echo -n "Network configuration input"
				echo -e "\t\t[\033[31m Error! \033[0m ]"        
           			usage 
		        fi
        		if [ $one -gt 255 -o $two -gt 255 -o $three -gt 255 -o $four -gt 255 ]; then
				echo -n "Network configuration input"
				echo -e "\t\t[\033[31m Error! \033[0m ]"        
           			usage 
		        fi
      		done < /tmp/tmp.setip
      	done
	rm /tmp/tmp.setip
}

check_ip()
{
	ip=`echo $1 | awk -F "." '{print $NF}'`
	gw=`echo $2 | awk -F "." '{print $NF}'`
	if [ $ip -le $gw ]; then
		echo -n "IP($1) and Gateway($2) input"
		echo -e "\t\t[\033[34m Error! \033[0m ]"        
		exit 0
	fi
	if [ $ip -eq 129 -o $ip -eq 130 -o $ip -eq 131 -o $ip -eq 132 -o $ip -eq 1 -o $ip -eq 2 -o $ip -eq 3 -o $ip -eq 4 ]; then
		echo "Please confirm the IP what your inputed: $1"
		echo "Continue or Stop? please keyin(y/n) and press Enter to continue:"
      		read key
		case $key in
		y | Y )
         		continue
         		;;
      		*)
			exit 0
		esac
	fi
}

setip()
{
	sed -i "/IPADDR=/s/=.*/='$ETH1'/" $ETH1_CONF
	sed -i "/NETMASK=/s/=.*/='$MASK1'/" $ETH1_CONF
	sed -i "/GATEWAY=/s/=.*/='$GATEWAY1'/" $ETH1_CONF
	sed -i "/STARTMODE=/s/=.*/='auto'/" $ETH1_CONF
	sed -i "/ONBOOT=/s/=.*/='yes'/" $ETH1_CONF

	if [ "$#" -eq 6 ]; then
	        TMP4=$4
        	TMP5=$5
	        TMP6=$6
        	ETH0=`echo $TMP4 | grep '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' `
	        MASK0=`echo $TMP5 | grep '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' `
        	GATEWAY0=`echo $TMP6 | grep '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' `
		
		sed -i "/IPADDR=/s/=.*/='$ETH0'/" $ETH0_CONF
		sed -i "/NETMASK=/s/=.*/='$MASK0'/" $ETH0_CONF
		sed -i "/GATEWAY=/s/=.*/='$GATEWAY0'/" $ETH0_CONF
		sed -i "/STARTMODE=/s/=.*/='auto'/" $ETH0_CONF
		sed -i "/ONBOOT=/s/=.*/='yes'/" $ETH0_CONF
	fi
	cp $SSH_36000 ${SSH_36000}_bak
	cp $SSH_56000 ${SSH_56000}_bak
	sed -e "/ListenAddress/ c \ \tListenAddress\t\t\t$ETH1" $SSH_36000 >/tmp/ssh.tmp
	mv /tmp/ssh.tmp $SSH_36000
	sed -e "/ListenAddress/ c \ \tListenAddress\t\t\t$ETH1" $SSH_56000 >/tmp/ssh.tmp
	mv /tmp/ssh.tmp $SSH_56000

	echo
	cat $ETH1_CONF
	echo
	echo
	cat $ETH0_CONF
	echo
	echo
	cat $SSH_36000 | grep Listen
	cat $SSH_56000 | grep Listen
}

if [ "$#" -eq 3 ]; then
	check_input $*
	check_ip $1 $3   
	setip $*
elif [ "$#" -eq 6 ]; then
	check_input $*
	check_ip $1 $3
	check_ip $4 $6
	setip $*
elif [ "$#" -eq 4 -a "$4" = "-f" ]; then 
	setip $1 $2 $3
elif [ "$#" -eq 7 -a "$7" = "-f" ]; then
	setip $1 $2 $3 $4 $5 $6
elif [ "$#" -eq 1 ] && [ "$1" = "-V" -o "$1" = "--version" ]; then
	echo "version: ${version}"
elif [ "$#" -eq 1 ] && [ "$1" = "-H" -o "$1" = "--help" ]; then
	usage
else
	usage
fi
#END OF FILE
